# Generated by Django 5.0.6 on 2024-09-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topics/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topics/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topics/'),
        ),
    ]
