# Generated by Django 5.0.4 on 2024-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_image_institution_image_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
