# Generated by Django 5.0.6 on 2024-08-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_image_institution_image_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institution'),
        ),
    ]
